language: node_js
node_js:
  - '5.0.0'
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
install:
  - npm install
matrix:
  fast_finish: true
script:
  - npm test